version: "3"

networks:
  mBlog:
    driver: bridge  
services: 
  mysql:
    container_name: mysql
    image: lihuangpeng/mysql:v1
    ports: 
      - "3306:3306"
    networks:
      - mBlog
    volumes:
      - /var/lib/docker/mysql/data:/usr/local/mysql/data
      - /var/lib/docker/mysql/etc:/usr/local/mysql/etc
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_PROJECT_USER=lhp
      - MYSQL_PROJECT_PASSWORD=1998lihuangpeng1

  php-fpm:
    container_name: php-fpm
    image: lihuangpeng/php-fpm:v1
    networks:
      - mBlog
    ports:
      - "9000:9000"
    volumes:
      - /var/lib/docker/php-fpm/etc:/usr/local/php74/etc
      - /var/lib/docker/php-fpm/log:/usr/local/php74/var/log
      - /var/www:/var/www
    restart: always

  nginx:
    container_name: nginx
    image: lihuangpeng/nginx:v1
    networks:
      - mBlog
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/lib/docker/nginx/conf:/usr/local/nginx/conf
      - /var/lib/docker/nginx/log:/usr/local/nginx/logs
      - /var/www:/var/www
    links:
      - "php-fpm:php"
    depends_on:
      - php-fpm

  redis:
    container_name: redis
    image: lihuangpeng/redis:v1
    networks:
      - mBlog
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/docker/redis/etc:/opt/app/redis/etc
      - /var/lib/docker/redis/data:/opt/app/redis/data
  memcached:
    container_name: memcached
    image: lihuangpeng/memcached:v1
    networks:
      - mBlog
    restart: always
    ports:
      - "11211:11211"
    environment:
      - MEMCACHE_MEMORY=256M
  rabbitmq:
    container_name: rabbitmq
    image: lihuangpeng/rabbitmq:v1
    networks:
      - mBlog
    restart: always
    ports:
      - "15627:15627"
      - "5627:5627"
      - "25627:25627"
    environment:
      - RABBITMQ_USER=lhp
      - RABBITMQ_PASSWORD=1998lihuangpeng1
    volumes:
      - /var/lib/docker/rabbitmq/var:/usr/local/rabbitmq/var
      - /var/lib/docker/rabbitmq/etc:/usr/local/rabbitmq/etc
